name: Release

on:
  workflow_dispatch:      # Manual trigger for release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        pypi_token: ${{ secrets.PYPI_TOKEN }}