name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master

env:
  PY_COLORS: 1

jobs:
  unit:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python-version: 3.6
            toxenv: py36
          - python-version: 3.7
            toxenv: py37
          - python-version: 3.8
            toxenv: py38
          - python-version: 3.9
            toxenv: py39
          - python-version: "3.10"
            toxenv: py310
#          - python-version: "3.10"
#            toxenv: smoke
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox pytest-github-actions-annotate-failures
      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

  coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install tox pytest-github-actions-annotate-failures
      - name: Run tests
        env:
          PY_COLORS: 1
          TOXENV: cover
        run: tox
      - name: Upload codecov coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unit
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}